baseURL = "https://karonrichards.co.uk/"
languageCode = "en-gb"
title = "Karon Richards"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  title = "Karon Richards"

  [params.logo]
  standard = "images/logo.svg"
  mobile = "images/logo-mobile.svg"
  alt = "Karon Richards"

  [params.homepage_meta_tags]
  meta_description = "Personal website for Karon Richards"
  meta_og_title = "Karon Richards"
  meta_og_type = "website"
  meta_og_url = "https://karonrichards.co.uk"
  meta_og_image = ""
  meta_og_description = "Personal website for Karon Richards"
  