baseURL = "https://karonrichards.co.uk/"
languageCode = "en-gb"
title = "Karon Richards"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]

  [params.logo]
  standard = "images/logo.svg"
  mobile = "images/logo-mobile.svg"
  alt = "Karon Richards"

  [params.homepage_meta_tags]
  meta_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_og_title = "Hugo Serif Theme"
  meta_og_type = "website"
  meta_og_url = "https://hugo-serif.netlify.com"
  meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-serif-theme/master/images/tn.png"
  meta_og_description = "Serif is a modern business theme for Hugo. It contains content types for the archetypical business website. The theme is fully responsive, blazing fast and artfully illustrated."
  meta_twitter_card = "summary"
  meta_twitter_site = "@zerostaticio"
  meta_twitter_creator = "@zerostaticio"
