---
new_page_extension: md
auto_deploy: false
admin_path: static/admin
webhook_url: ''
sections:
- type: directory
  path: content
  label: Pages
  create: documents
  match: "*"
- type: document
  path: exampleSite/config.toml
  label: Config
  templates:
  - config
- type: document
  path: exampleSite/content/_index.md
  label: Home
  templates:
  - home
- type: document
  path: exampleSite/content/404/_index.md
  label: '404'
  templates:
  - pagenotfound
- type: directory
  path: exampleSite/content
  label: Basic Page
  create: all
  match: "*.md"
  exclude: "{_index.md,_index.md}"
  templates:
  - basicpage
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  exclude: "{_index.md,blog/_index.md}"
upload_dir: static/images
public_path: "/static/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_VERSION=0.68.3
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.63.2
